[package]
name = "rusty-counter"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11.6"
dotenv = "0.15"